#!/usr/bin/env python3
"""Tests for check_release_version.py."""

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).with_name("check_release_version.py")


class CheckReleaseVersionTests(unittest.TestCase):
    def run_check(
        self,
        package_version: str,
        release_version: str,
        update: bool = False,
        line_ending: str = "\n",
    ) -> tuple[subprocess.CompletedProcess[str], str, str]:
        with tempfile.TemporaryDirectory() as directory:
            manifest_path = Path(directory) / "Cargo.toml"
            source_path = Path(directory) / "src"
            source_path.mkdir()
            (source_path / "lib.rs").write_text("", encoding="utf-8")
            manifest = (
                "[package]\n"
                'name = "version-check-fixture"\n'
                f'version = "{package_version}"\n'
                'edition = "2021"\n'
            )
            manifest_path.write_bytes(manifest.replace("\n", line_ending).encode())
            lockfile = (
                "# This file is automatically @generated by Cargo.\n"
                "# It is not intended for manual editing.\n"
                "version = 4\n\n"
                "[[package]]\n"
                'name = "version-check-fixture"\n'
                f'version = "{package_version}"\n'
            )
            (Path(directory) / "Cargo.lock").write_bytes(
                lockfile.replace("\n", line_ending).encode()
            )
            command = [
                sys.executable,
                str(SCRIPT),
                release_version,
                "--manifest-path",
                str(manifest_path),
            ]
            if update:
                command.append("--update")
            result = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
            )
            lock_path = Path(directory) / "Cargo.lock"
            lock_text = (
                lock_path.read_bytes().decode() if lock_path.exists() else ""
            )
            return result, manifest_path.read_bytes().decode(), lock_text

    def test_matching_prerelease_succeeds(self) -> None:
        result, _manifest, _lock = self.run_check("0.21.0-rc4", "0.21.0-rc4")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(
            "Cargo package version 0.21.0-rc4 matches the release version",
            result.stdout,
        )

    def test_mismatched_version_has_clear_diagnostic(self) -> None:
        result, _manifest, _lock = self.run_check("0.21.0-rc4", "0.21.0")

        self.assertEqual(result.returncode, 1)
        self.assertIn(
            "error: release version mismatch: Cargo package version is 0.21.0-rc4, "
            "but the validated release version is 0.21.0",
            result.stderr,
        )

    def test_update_synchronizes_manifest_and_lockfile(self) -> None:
        result, manifest, lockfile = self.run_check(
            "0.21.0-rc4", "0.21.0-rc5", update=True, line_ending="\r\n"
        )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('version = "0.21.0-rc5"', manifest)
        self.assertIn('version = "0.21.0-rc5"', lockfile)
        self.assertNotIn("\r\r\n", manifest)
        self.assertNotIn("\r\r\n", lockfile)


if __name__ == "__main__":
    unittest.main()
