//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicIsize, Ordering};
use std::alloc::Layout;

/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub const fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    ROC_ERASED_CALLABLE_CAPTURE_OFFSET + capture_size
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let base = roc_host.alloc(alignment, extra_bytes + roc_erased_callable_payload_size(capture_size)) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
pub fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { roc_host.alloc(alloc_alignment, header_bytes + payload_size) } as *mut u8;
    let data = unsafe { base.add(header_bytes) };
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    decref_box_with(data_ptr, core::mem::align_of::<usize>(), None, roc_host);
}

/// Increment a boxed function closure.
pub fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    incref_box(callable as RocBox, amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    decref_box_with(
        callable as RocBox,
        ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
        Some(drop_erased_callable_payload),
        roc_host,
    );
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
        if prev == 1 {
            if let Some(callback) = payload_decref {
                callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
            }
            free_box_allocation(data, payload_alignment, payload_decref.is_some(), roc_host);
        }
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_decref.is_some(), roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Relaxed) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`, assuming valid UTF-8.
    pub fn as_str(&self) -> &str {
        // SAFETY: Roc guarantees all strings are valid UTF-8.
        unsafe { core::str::from_utf8_unchecked(self.as_slice()) }
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = ptr_width + slice.len();
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: slice.len() << 1,
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let ptr_width = core::mem::size_of::<usize>();
                let base = alloc_ptr.sub(ptr_width) as *mut c_void;
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("value", &self.as_str())
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { 2 * ptr_width } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    pub fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = length * core::mem::size_of::<T>();
        let total = data_bytes + header_bytes;
        let base = unsafe { roc_host.alloc(align, total) };
        let data_ptr = unsafe { (base as *mut u8).add(header_bytes) };
        // Write refcount = 1
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: length << 1,
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    pub fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = Self::allocate(slice.len(), roc_host);
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let base = alloc_ptr.sub(header_bytes) as *mut c_void;
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Relaxed) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Element type for Cmd
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Cmd {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<Cmd>() == 80, "Cmd size mismatch");
const _: () = assert!(core::mem::align_of::<Cmd>() == 8, "Cmd alignment mismatch");

/// Element type for __AnonStruct9
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct9 {
    pub stderr_bytes: RocListWith<u8, false>,
    pub stdout_bytes: RocListWith<u8, false>,
    pub exit_code: i32,
}

const _: () = assert!(core::mem::size_of::<AnonStruct9>() == 56, "AnonStruct9 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct9>() == 8, "AnonStruct9 alignment mismatch");

/// Element type for __AnonStruct12
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct12 {
    pub stderr_bytes: RocListWith<u8, false>,
    pub stdout_bytes: RocListWith<u8, false>,
}

const _: () = assert!(core::mem::size_of::<AnonStruct12>() == 48, "AnonStruct12 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct12>() == 8, "AnonStruct12 alignment mismatch");

/// Element type for __AnonStruct44
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct44 {
    pub is_dir: bool,
    pub is_file: bool,
    pub is_sym_link: bool,
}

const _: () = assert!(core::mem::size_of::<AnonStruct44>() == 3, "AnonStruct44 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct44>() == 1, "AnonStruct44 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType0Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType0 {
    pub payload: TryType0Payload,
    pub tag: TryType0Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType0Payload {
    pub err: core::mem::ManuallyDrop<IOErrType1>,
    pub ok: core::mem::ManuallyDrop<i32>,
}

const _: () = assert!(core::mem::size_of::<TryType0>() == 40, "TryType0 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType0>() == 8, "TryType0 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType1Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType1 {
    pub payload: IOErrType1Payload,
    pub tag: IOErrType1Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType1Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType1>() == 32, "IOErrType1 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType1>() == 8, "IOErrType1 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType7Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType7 {
    pub payload: TryType7Payload,
    pub tag: TryType7Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType7Payload {
    pub err: core::mem::ManuallyDrop<TryType8>,
    pub ok: core::mem::ManuallyDrop<AnonStruct12>,
}

const _: () = assert!(core::mem::size_of::<TryType7>() == 72, "TryType7 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType7>() == 8, "TryType7 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType8Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType8 {
    pub payload: TryType8Payload,
    pub tag: TryType8Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType8Payload {
    pub err: core::mem::ManuallyDrop<IOErrType1>,
    pub ok: core::mem::ManuallyDrop<AnonStruct9>,
}

const _: () = assert!(core::mem::size_of::<TryType8>() == 64, "TryType8 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType8>() == 8, "TryType8 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType13Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType13 {
    pub payload: TryType13Payload,
    pub tag: TryType13Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType13Payload {
    pub err: core::mem::ManuallyDrop<IOErrType15>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType13>() == 40, "TryType13 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType13>() == 8, "TryType13 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType15Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType15 {
    pub payload: IOErrType15Payload,
    pub tag: IOErrType15Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType15Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType15>() == 32, "IOErrType15 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType15>() == 8, "IOErrType15 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType18Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType18 {
    pub payload: TryType18Payload,
    pub tag: TryType18Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType18Payload {
    pub err: core::mem::ManuallyDrop<IOErrType15>,
    pub ok: core::mem::ManuallyDrop<RocList<RocStr>>,
}

const _: () = assert!(core::mem::size_of::<TryType18>() == 40, "TryType18 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType18>() == 8, "TryType18 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType20Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType20 {
    pub payload: TryType20Payload,
    pub tag: TryType20Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType20Payload {
    pub err: core::mem::ManuallyDrop<RocStr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType20>() == 32, "TryType20 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType20>() == 8, "TryType20 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType23Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType23 {
    pub payload: TryType23Payload,
    pub tag: TryType23Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType23Payload {
    pub err: core::mem::ManuallyDrop<*mut c_void>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType23>() == 32, "TryType23 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType23>() == 8, "TryType23 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType26Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType26 {
    pub payload: TryType26Payload,
    pub tag: TryType26Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType26Payload {
    pub err: core::mem::ManuallyDrop<*mut c_void>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType26>() == 32, "TryType26 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType26>() == 8, "TryType26 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType28Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType28 {
    pub payload: TryType28Payload,
    pub tag: TryType28Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType28Payload {
    pub err: core::mem::ManuallyDrop<IOErrType30>,
    pub ok: core::mem::ManuallyDrop<RocListWith<u8, false>>,
}

const _: () = assert!(core::mem::size_of::<TryType28>() == 40, "TryType28 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType28>() == 8, "TryType28 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType30Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType30 {
    pub payload: IOErrType30Payload,
    pub tag: IOErrType30Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType30Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType30>() == 32, "IOErrType30 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType30>() == 8, "IOErrType30 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType34Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType34 {
    pub payload: TryType34Payload,
    pub tag: TryType34Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType34Payload {
    pub err: core::mem::ManuallyDrop<IOErrType30>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType34>() == 40, "TryType34 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType34>() == 8, "TryType34 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType36Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType36 {
    pub payload: TryType36Payload,
    pub tag: TryType36Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType36Payload {
    pub err: core::mem::ManuallyDrop<IOErrType30>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType36>() == 40, "TryType36 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType36>() == 8, "TryType36 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType37Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType37 {
    pub payload: TryType37Payload,
    pub tag: TryType37Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType37Payload {
    pub err: core::mem::ManuallyDrop<*mut c_void>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType37>() == 32, "TryType37 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType37>() == 8, "TryType37 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType41Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType41 {
    pub payload: TryType41Payload,
    pub tag: TryType41Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType41Payload {
    pub err: core::mem::ManuallyDrop<IOErrType42>,
    pub ok: core::mem::ManuallyDrop<AnonStruct44>,
}

const _: () = assert!(core::mem::size_of::<TryType41>() == 40, "TryType41 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType41>() == 8, "TryType41 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType42Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType42 {
    pub payload: IOErrType42Payload,
    pub tag: IOErrType42Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType42Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType42>() == 32, "IOErrType42 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType42>() == 8, "IOErrType42 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType48Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType48 {
    pub payload: TryType48Payload,
    pub tag: TryType48Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType48Payload {
    pub err: core::mem::ManuallyDrop<IOErrType50>,
    pub ok: core::mem::ManuallyDrop<u64>,
}

const _: () = assert!(core::mem::size_of::<TryType48>() == 40, "TryType48 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType48>() == 8, "TryType48 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType50Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType50 {
    pub payload: IOErrType50Payload,
    pub tag: IOErrType50Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType50Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType50>() == 32, "IOErrType50 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType50>() == 8, "IOErrType50 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType54Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType54 {
    pub payload: TryType54Payload,
    pub tag: TryType54Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType54Payload {
    pub err: core::mem::ManuallyDrop<IOErrType50>,
    pub ok: core::mem::ManuallyDrop<u32>,
}

const _: () = assert!(core::mem::size_of::<TryType54>() == 40, "TryType54 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType54>() == 8, "TryType54 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType58Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType58 {
    pub payload: TryType58Payload,
    pub tag: TryType58Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType58Payload {
    pub err: core::mem::ManuallyDrop<IOErrType60>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType58>() == 40, "TryType58 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType58>() == 8, "TryType58 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType60Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType60 {
    pub payload: IOErrType60Payload,
    pub tag: IOErrType60Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType60Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType60>() == 32, "IOErrType60 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType60>() == 8, "IOErrType60 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType65Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType65 {
    pub payload: TryType65Payload,
    pub tag: TryType65Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType65Payload {
    pub err: core::mem::ManuallyDrop<EndOfFileOrStdinErr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType65>() == 48, "TryType65 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType65>() == 8, "TryType65 alignment mismatch");

/// Tag discriminant for EndOfFileOrStdinErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EndOfFileOrStdinErrTag {
    EndOfFile = 0,
    StdinErr = 1,
}

/// Tag union: EndOfFileOrStdinErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct EndOfFileOrStdinErr {
    pub payload: EndOfFileOrStdinErrPayload,
    pub tag: EndOfFileOrStdinErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union EndOfFileOrStdinErrPayload {
    pub end_of_file: [u8; 0],
    pub stdin_err: core::mem::ManuallyDrop<IOErrType67>,
}

const _: () = assert!(core::mem::size_of::<EndOfFileOrStdinErr>() == 40, "EndOfFileOrStdinErr size mismatch");
const _: () = assert!(core::mem::align_of::<EndOfFileOrStdinErr>() == 8, "EndOfFileOrStdinErr alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType67Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType67 {
    pub payload: IOErrType67Payload,
    pub tag: IOErrType67Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType67Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType67>() == 32, "IOErrType67 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType67>() == 8, "IOErrType67 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType70Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType70 {
    pub payload: TryType70Payload,
    pub tag: TryType70Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType70Payload {
    pub err: core::mem::ManuallyDrop<EndOfFileOrStdinErr>,
    pub ok: core::mem::ManuallyDrop<RocListWith<u8, false>>,
}

const _: () = assert!(core::mem::size_of::<TryType70>() == 48, "TryType70 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType70>() == 8, "TryType70 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType73Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType73 {
    pub payload: TryType73Payload,
    pub tag: TryType73Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType73Payload {
    pub err: core::mem::ManuallyDrop<IOErrType67>,
    pub ok: core::mem::ManuallyDrop<RocListWith<u8, false>>,
}

const _: () = assert!(core::mem::size_of::<TryType73>() == 40, "TryType73 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType73>() == 8, "TryType73 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType75Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType75 {
    pub payload: TryType75Payload,
    pub tag: TryType75Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType75Payload {
    pub err: core::mem::ManuallyDrop<IOErrType77>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType75>() == 40, "TryType75 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType75>() == 8, "TryType75 alignment mismatch");

/// Tag discriminant for IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IOErrType77Tag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IOErrType77 {
    pub payload: IOErrType77Payload,
    pub tag: IOErrType77Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union IOErrType77Payload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<IOErrType77>() == 32, "IOErrType77 size mismatch");
const _: () = assert!(core::mem::align_of::<IOErrType77>() == 8, "IOErrType77 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType88Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType88 {
    pub payload: TryType88Payload,
    pub tag: TryType88Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType88Payload {
    pub err: core::mem::ManuallyDrop<i32>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType88>() == 8, "TryType88 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType88>() == 4, "TryType88 alignment mismatch");

/// Arguments for Cmd.host_exec_exit_code!
/// Roc signature: Cmd => Try(I32, IOErr)
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdHostExecExitCodeArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<CmdHostExecExitCodeArgs>() == 80, "CmdHostExecExitCodeArgs size mismatch");
const _: () = assert!(core::mem::align_of::<CmdHostExecExitCodeArgs>() == 8, "CmdHostExecExitCodeArgs alignment mismatch");

/// Arguments for Cmd.host_exec_output!
/// Roc signature: Cmd => Try({ stderr_bytes : List(U8), stdout_bytes : List(U8) }, Try({ exit_code : I32, stderr_bytes : List(U8), stdout_bytes : List(U8) }, IOErr))
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdHostExecOutputArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<CmdHostExecOutputArgs>() == 80, "CmdHostExecOutputArgs size mismatch");
const _: () = assert!(core::mem::align_of::<CmdHostExecOutputArgs>() == 8, "CmdHostExecOutputArgs alignment mismatch");

/// Arguments for Dir.create!
/// Roc signature: Str => Try({}, [DirErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirCreateArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.create_all!
/// Roc signature: Str => Try({}, [DirErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirCreateAllArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.delete_all!
/// Roc signature: Str => Try({}, [DirErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirDeleteAllArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.delete_empty!
/// Roc signature: Str => Try({}, [DirErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirDeleteEmptyArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.list!
/// Roc signature: Str => Try(List(Str), [DirErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirListArgs {
    pub arg0: RocStr,
}

/// Arguments for Env.var!
/// Roc signature: Str => Try(Str, [VarNotFound(Str)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct EnvVarArgs {
    pub arg0: RocStr,
}

/// Arguments for File.delete!
/// Roc signature: Str => Try({}, [FileErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileDeleteArgs {
    pub arg0: RocStr,
}

/// Arguments for File.read_bytes!
/// Roc signature: Str => Try(List(U8), [FileErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileReadBytesArgs {
    pub arg0: RocStr,
}

/// Arguments for File.read_utf8!
/// Roc signature: Str => Try(Str, [FileErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileReadUtf8Args {
    pub arg0: RocStr,
}

/// Arguments for File.write_bytes!
/// Roc signature: Str, List(U8) => Try({}, [FileErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileWriteBytesArgs {
    pub arg0: RocStr,
    pub arg1: RocListWith<u8, false>,
}

/// Arguments for File.write_utf8!
/// Roc signature: Str, Str => Try({}, [FileErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileWriteUtf8Args {
    pub arg0: RocStr,
    pub arg1: RocStr,
}

/// Arguments for Path.host_path_type!
/// Roc signature: List(U8) => Try({ is_dir : Bool, is_file : Bool, is_sym_link : Bool }, IOErr)
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PathHostPathTypeArgs {
    pub arg0: RocListWith<u8, false>,
}

/// Arguments for Sleep.millis!
/// Roc signature: U64 => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SleepMillisArgs {
    pub arg0: u64,
}

/// Arguments for Stderr.line!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stderr.write!
/// Roc signature: Str => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrWriteArgs {
    pub arg0: RocStr,
}

/// Arguments for Stderr.write_bytes!
/// Roc signature: List(U8) => Try({}, [StderrErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrWriteBytesArgs {
    pub arg0: RocListWith<u8, false>,
}

/// Arguments for Stdout.line!
/// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StdoutLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stdout.write!
/// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StdoutWriteArgs {
    pub arg0: RocStr,
}

/// Arguments for Stdout.write_bytes!
/// Roc signature: List(U8) => Try({}, [StdoutErr(IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StdoutWriteBytesArgs {
    pub arg0: RocListWith<u8, false>,
}

// =============================================================================
// Generated Refcount Helpers
// =============================================================================

/// Recursively decrement Roc-owned payloads in TryType0.
pub fn decref_try_type0(value: TryType0, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type1(payload, roc_host);
        },
        TryType0Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType0.
pub fn incref_try_type0(value: TryType0, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type1(payload, amount);
        },
        TryType0Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType1.
pub fn decref_ioerr_type1(value: IOErrType1, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType1Tag::AlreadyExists => {},
        IOErrType1Tag::BrokenPipe => {},
        IOErrType1Tag::Interrupted => {},
        IOErrType1Tag::NotFound => {},
        IOErrType1Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType1Tag::OutOfMemory => {},
        IOErrType1Tag::PermissionDenied => {},
        IOErrType1Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType1.
pub fn incref_ioerr_type1(value: IOErrType1, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType1Tag::AlreadyExists => {},
        IOErrType1Tag::BrokenPipe => {},
        IOErrType1Tag::Interrupted => {},
        IOErrType1Tag::NotFound => {},
        IOErrType1Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType1Tag::OutOfMemory => {},
        IOErrType1Tag::PermissionDenied => {},
        IOErrType1Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned fields in Cmd.
pub fn decref_cmd(value: Cmd, roc_host: &RocHost) {
    {
        let list = value.args;
        if list.has_one_ref() {
            for item in list.allocation_items() {
                    (*item).decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        let list = value.envs;
        if list.has_one_ref() {
            for item in list.allocation_items() {
                    (*item).decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.program.decref(roc_host);
}

/// Increment Roc-owned fields in Cmd.
pub fn incref_cmd(value: Cmd, amount: isize) {
    value.args.incref(amount);
    value.envs.incref(amount);
    value.program.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType7.
pub fn decref_try_type7(value: TryType7, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType7Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_try_type8(payload, roc_host);
        },
        TryType7Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            decref_anon_struct12(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType7.
pub fn incref_try_type7(value: TryType7, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType7Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_try_type8(payload, amount);
        },
        TryType7Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            incref_anon_struct12(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType8.
pub fn decref_try_type8(value: TryType8, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType8Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type1(payload, roc_host);
        },
        TryType8Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            decref_anon_struct9(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType8.
pub fn incref_try_type8(value: TryType8, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType8Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type1(payload, amount);
        },
        TryType8Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            incref_anon_struct9(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct9.
pub fn decref_anon_struct9(value: AnonStruct9, roc_host: &RocHost) {
    {
        let list = value.stderr_bytes;
        list.decref(roc_host);
    }
    {
        let list = value.stdout_bytes;
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in AnonStruct9.
pub fn incref_anon_struct9(value: AnonStruct9, amount: isize) {
    value.stderr_bytes.incref(amount);
    value.stdout_bytes.incref(amount);
}

/// Recursively decrement Roc-owned fields in AnonStruct12.
pub fn decref_anon_struct12(value: AnonStruct12, roc_host: &RocHost) {
    {
        let list = value.stderr_bytes;
        list.decref(roc_host);
    }
    {
        let list = value.stdout_bytes;
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in AnonStruct12.
pub fn incref_anon_struct12(value: AnonStruct12, amount: isize) {
    value.stderr_bytes.incref(amount);
    value.stdout_bytes.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType13.
pub fn decref_try_type13(value: TryType13, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType13Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type15(payload, roc_host);
        },
        TryType13Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType13.
pub fn incref_try_type13(value: TryType13, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType13Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type15(payload, amount);
        },
        TryType13Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType15.
pub fn decref_ioerr_type15(value: IOErrType15, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType15Tag::AlreadyExists => {},
        IOErrType15Tag::BrokenPipe => {},
        IOErrType15Tag::Interrupted => {},
        IOErrType15Tag::NotFound => {},
        IOErrType15Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType15Tag::OutOfMemory => {},
        IOErrType15Tag::PermissionDenied => {},
        IOErrType15Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType15.
pub fn incref_ioerr_type15(value: IOErrType15, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType15Tag::AlreadyExists => {},
        IOErrType15Tag::BrokenPipe => {},
        IOErrType15Tag::Interrupted => {},
        IOErrType15Tag::NotFound => {},
        IOErrType15Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType15Tag::OutOfMemory => {},
        IOErrType15Tag::PermissionDenied => {},
        IOErrType15Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType18.
pub fn decref_try_type18(value: TryType18, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType18Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type15(payload, roc_host);
        },
        TryType18Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                if list.has_one_ref() {
                    for item in list.allocation_items() {
                            (*item).decref(roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType18.
pub fn incref_try_type18(value: TryType18, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType18Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type15(payload, amount);
        },
        TryType18Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType20.
pub fn decref_try_type20(value: TryType20, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType20Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.decref(roc_host);
        },
        TryType20Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType20.
pub fn incref_try_type20(value: TryType20, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType20Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            payload.incref(amount);
        },
        TryType20Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType23.
pub fn decref_try_type23(value: TryType23, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType23Tag::Err => {},
        TryType23Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType23.
pub fn incref_try_type23(value: TryType23, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType23Tag::Err => {},
        TryType23Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType26.
pub fn decref_try_type26(value: TryType26, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType26Tag::Err => {},
        TryType26Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType26.
pub fn incref_try_type26(value: TryType26, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType26Tag::Err => {},
        TryType26Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType28.
pub fn decref_try_type28(value: TryType28, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType28Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type30(payload, roc_host);
        },
        TryType28Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType28.
pub fn incref_try_type28(value: TryType28, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType28Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type30(payload, amount);
        },
        TryType28Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType30.
pub fn decref_ioerr_type30(value: IOErrType30, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType30Tag::AlreadyExists => {},
        IOErrType30Tag::BrokenPipe => {},
        IOErrType30Tag::Interrupted => {},
        IOErrType30Tag::NotFound => {},
        IOErrType30Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType30Tag::OutOfMemory => {},
        IOErrType30Tag::PermissionDenied => {},
        IOErrType30Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType30.
pub fn incref_ioerr_type30(value: IOErrType30, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType30Tag::AlreadyExists => {},
        IOErrType30Tag::BrokenPipe => {},
        IOErrType30Tag::Interrupted => {},
        IOErrType30Tag::NotFound => {},
        IOErrType30Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType30Tag::OutOfMemory => {},
        IOErrType30Tag::PermissionDenied => {},
        IOErrType30Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType34.
pub fn decref_try_type34(value: TryType34, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType34Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type30(payload, roc_host);
        },
        TryType34Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType34.
pub fn incref_try_type34(value: TryType34, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType34Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type30(payload, amount);
        },
        TryType34Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType36.
pub fn decref_try_type36(value: TryType36, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType36Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type30(payload, roc_host);
        },
        TryType36Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType36.
pub fn incref_try_type36(value: TryType36, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType36Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type30(payload, amount);
        },
        TryType36Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType37.
pub fn decref_try_type37(value: TryType37, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType37Tag::Err => {},
        TryType37Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType37.
pub fn incref_try_type37(value: TryType37, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType37Tag::Err => {},
        TryType37Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType41.
pub fn decref_try_type41(value: TryType41, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType41Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type42(payload, roc_host);
        },
        TryType41Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            decref_anon_struct44(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType41.
pub fn incref_try_type41(value: TryType41, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType41Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type42(payload, amount);
        },
        TryType41Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            incref_anon_struct44(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType42.
pub fn decref_ioerr_type42(value: IOErrType42, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType42Tag::AlreadyExists => {},
        IOErrType42Tag::BrokenPipe => {},
        IOErrType42Tag::Interrupted => {},
        IOErrType42Tag::NotFound => {},
        IOErrType42Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType42Tag::OutOfMemory => {},
        IOErrType42Tag::PermissionDenied => {},
        IOErrType42Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType42.
pub fn incref_ioerr_type42(value: IOErrType42, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType42Tag::AlreadyExists => {},
        IOErrType42Tag::BrokenPipe => {},
        IOErrType42Tag::Interrupted => {},
        IOErrType42Tag::NotFound => {},
        IOErrType42Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType42Tag::OutOfMemory => {},
        IOErrType42Tag::PermissionDenied => {},
        IOErrType42Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct44.
pub fn decref_anon_struct44(value: AnonStruct44, roc_host: &RocHost) {
    let _ = value;
    let _ = roc_host;
}

/// Increment Roc-owned fields in AnonStruct44.
pub fn incref_anon_struct44(value: AnonStruct44, amount: isize) {
    let _ = value;
    let _ = amount;
}

/// Recursively decrement Roc-owned payloads in TryType48.
pub fn decref_try_type48(value: TryType48, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType48Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type50(payload, roc_host);
        },
        TryType48Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType48.
pub fn incref_try_type48(value: TryType48, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType48Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type50(payload, amount);
        },
        TryType48Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType50.
pub fn decref_ioerr_type50(value: IOErrType50, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType50Tag::AlreadyExists => {},
        IOErrType50Tag::BrokenPipe => {},
        IOErrType50Tag::Interrupted => {},
        IOErrType50Tag::NotFound => {},
        IOErrType50Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType50Tag::OutOfMemory => {},
        IOErrType50Tag::PermissionDenied => {},
        IOErrType50Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType50.
pub fn incref_ioerr_type50(value: IOErrType50, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType50Tag::AlreadyExists => {},
        IOErrType50Tag::BrokenPipe => {},
        IOErrType50Tag::Interrupted => {},
        IOErrType50Tag::NotFound => {},
        IOErrType50Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType50Tag::OutOfMemory => {},
        IOErrType50Tag::PermissionDenied => {},
        IOErrType50Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType54.
pub fn decref_try_type54(value: TryType54, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType54Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type50(payload, roc_host);
        },
        TryType54Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType54.
pub fn incref_try_type54(value: TryType54, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType54Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type50(payload, amount);
        },
        TryType54Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType58.
pub fn decref_try_type58(value: TryType58, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType58Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type60(payload, roc_host);
        },
        TryType58Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType58.
pub fn incref_try_type58(value: TryType58, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType58Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type60(payload, amount);
        },
        TryType58Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType60.
pub fn decref_ioerr_type60(value: IOErrType60, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType60Tag::AlreadyExists => {},
        IOErrType60Tag::BrokenPipe => {},
        IOErrType60Tag::Interrupted => {},
        IOErrType60Tag::NotFound => {},
        IOErrType60Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType60Tag::OutOfMemory => {},
        IOErrType60Tag::PermissionDenied => {},
        IOErrType60Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType60.
pub fn incref_ioerr_type60(value: IOErrType60, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType60Tag::AlreadyExists => {},
        IOErrType60Tag::BrokenPipe => {},
        IOErrType60Tag::Interrupted => {},
        IOErrType60Tag::NotFound => {},
        IOErrType60Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType60Tag::OutOfMemory => {},
        IOErrType60Tag::PermissionDenied => {},
        IOErrType60Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType65.
pub fn decref_try_type65(value: TryType65, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType65Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_end_of_file_or_stdin_err(payload, roc_host);
        },
        TryType65Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType65.
pub fn incref_try_type65(value: TryType65, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType65Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_end_of_file_or_stdin_err(payload, amount);
        },
        TryType65Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in EndOfFileOrStdinErr.
pub fn decref_end_of_file_or_stdin_err(value: EndOfFileOrStdinErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        EndOfFileOrStdinErrTag::EndOfFile => {},
        EndOfFileOrStdinErrTag::StdinErr => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.stdin_err);
            decref_ioerr_type67(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in EndOfFileOrStdinErr.
pub fn incref_end_of_file_or_stdin_err(value: EndOfFileOrStdinErr, amount: isize) {
    let _ = amount;
    match value.tag {
        EndOfFileOrStdinErrTag::EndOfFile => {},
        EndOfFileOrStdinErrTag::StdinErr => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.stdin_err);
            incref_ioerr_type67(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType67.
pub fn decref_ioerr_type67(value: IOErrType67, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType67Tag::AlreadyExists => {},
        IOErrType67Tag::BrokenPipe => {},
        IOErrType67Tag::Interrupted => {},
        IOErrType67Tag::NotFound => {},
        IOErrType67Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType67Tag::OutOfMemory => {},
        IOErrType67Tag::PermissionDenied => {},
        IOErrType67Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType67.
pub fn incref_ioerr_type67(value: IOErrType67, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType67Tag::AlreadyExists => {},
        IOErrType67Tag::BrokenPipe => {},
        IOErrType67Tag::Interrupted => {},
        IOErrType67Tag::NotFound => {},
        IOErrType67Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType67Tag::OutOfMemory => {},
        IOErrType67Tag::PermissionDenied => {},
        IOErrType67Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType70.
pub fn decref_try_type70(value: TryType70, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType70Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_end_of_file_or_stdin_err(payload, roc_host);
        },
        TryType70Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType70.
pub fn incref_try_type70(value: TryType70, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType70Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_end_of_file_or_stdin_err(payload, amount);
        },
        TryType70Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType73.
pub fn decref_try_type73(value: TryType73, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType73Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type67(payload, roc_host);
        },
        TryType73Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType73.
pub fn incref_try_type73(value: TryType73, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType73Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type67(payload, amount);
        },
        TryType73Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType75.
pub fn decref_try_type75(value: TryType75, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType75Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_ioerr_type77(payload, roc_host);
        },
        TryType75Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType75.
pub fn incref_try_type75(value: TryType75, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType75Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_ioerr_type77(payload, amount);
        },
        TryType75Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in IOErrType77.
pub fn decref_ioerr_type77(value: IOErrType77, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        IOErrType77Tag::AlreadyExists => {},
        IOErrType77Tag::BrokenPipe => {},
        IOErrType77Tag::Interrupted => {},
        IOErrType77Tag::NotFound => {},
        IOErrType77Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        IOErrType77Tag::OutOfMemory => {},
        IOErrType77Tag::PermissionDenied => {},
        IOErrType77Tag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in IOErrType77.
pub fn incref_ioerr_type77(value: IOErrType77, amount: isize) {
    let _ = amount;
    match value.tag {
        IOErrType77Tag::AlreadyExists => {},
        IOErrType77Tag::BrokenPipe => {},
        IOErrType77Tag::Interrupted => {},
        IOErrType77Tag::NotFound => {},
        IOErrType77Tag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        IOErrType77Tag::OutOfMemory => {},
        IOErrType77Tag::PermissionDenied => {},
        IOErrType77Tag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType88.
pub fn decref_try_type88(value: TryType88, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType88Tag::Err => {},
        TryType88Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType88.
pub fn incref_try_type88(value: TryType88, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType88Tag::Err => {},
        TryType88Tag::Ok => {},
    }
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Hosted symbol for Cmd.host_exec_exit_code!
    /// Roc signature: Cmd => Try(I32, IOErr)
    pub fn hosted_cmd_host_exec_exit_code(arg0: Cmd) -> TryType0;

    /// Hosted symbol for Cmd.host_exec_output!
    /// Roc signature: Cmd => Try({ stderr_bytes : List(U8), stdout_bytes : List(U8) }, Try({ exit_code : I32, stderr_bytes : List(U8), stdout_bytes : List(U8) }, IOErr))
    pub fn hosted_cmd_host_exec_output(arg0: Cmd) -> TryType7;

    /// Hosted symbol for Dir.create!
    /// Roc signature: Str => Try({}, [DirErr(IOErr)])
    pub fn hosted_dir_create(arg0: RocStr) -> TryType13;

    /// Hosted symbol for Dir.create_all!
    /// Roc signature: Str => Try({}, [DirErr(IOErr)])
    pub fn hosted_dir_create_all(arg0: RocStr) -> TryType13;

    /// Hosted symbol for Dir.delete_all!
    /// Roc signature: Str => Try({}, [DirErr(IOErr)])
    pub fn hosted_dir_delete_all(arg0: RocStr) -> TryType13;

    /// Hosted symbol for Dir.delete_empty!
    /// Roc signature: Str => Try({}, [DirErr(IOErr)])
    pub fn hosted_dir_delete_empty(arg0: RocStr) -> TryType13;

    /// Hosted symbol for Dir.list!
    /// Roc signature: Str => Try(List(Str), [DirErr(IOErr)])
    pub fn hosted_dir_list(arg0: RocStr) -> TryType18;

    /// Hosted symbol for Env.cwd!
    /// Roc signature: {} => Try(Str, [CwdUnavailable])
    pub fn hosted_env_cwd() -> TryType23;

    /// Hosted symbol for Env.exe_path!
    /// Roc signature: {} => Try(Str, [ExePathUnavailable])
    pub fn hosted_env_exe_path() -> TryType26;

    /// Hosted symbol for Env.var!
    /// Roc signature: Str => Try(Str, [VarNotFound(Str)])
    pub fn hosted_env_var(arg0: RocStr) -> TryType20;

    /// Hosted symbol for File.delete!
    /// Roc signature: Str => Try({}, [FileErr(IOErr)])
    pub fn hosted_file_delete(arg0: RocStr) -> TryType34;

    /// Hosted symbol for File.read_bytes!
    /// Roc signature: Str => Try(List(U8), [FileErr(IOErr)])
    pub fn hosted_file_read_bytes(arg0: RocStr) -> TryType28;

    /// Hosted symbol for File.read_utf8!
    /// Roc signature: Str => Try(Str, [FileErr(IOErr)])
    pub fn hosted_file_read_utf8(arg0: RocStr) -> TryType36;

    /// Hosted symbol for File.write_bytes!
    /// Roc signature: Str, List(U8) => Try({}, [FileErr(IOErr)])
    pub fn hosted_file_write_bytes(arg0: RocStr, arg1: RocListWith<u8, false>) -> TryType34;

    /// Hosted symbol for File.write_utf8!
    /// Roc signature: Str, Str => Try({}, [FileErr(IOErr)])
    pub fn hosted_file_write_utf8(arg0: RocStr, arg1: RocStr) -> TryType34;

    /// Hosted symbol for Locale.all!
    /// Roc signature: {} => List(Str)
    pub fn hosted_locale_all() -> RocList<RocStr>;

    /// Hosted symbol for Locale.get!
    /// Roc signature: {} => Try(Str, [NotAvailable])
    pub fn hosted_locale_get() -> TryType37;

    /// Hosted symbol for Path.host_path_type!
    /// Roc signature: List(U8) => Try({ is_dir : Bool, is_file : Bool, is_sym_link : Bool }, IOErr)
    pub fn hosted_path_type(arg0: RocListWith<u8, false>) -> TryType41;

    /// Hosted symbol for Random.seed_u32!
    /// Roc signature: {} => Try(U32, [RandomErr(IOErr)])
    pub fn hosted_random_seed_u32() -> TryType54;

    /// Hosted symbol for Random.seed_u64!
    /// Roc signature: {} => Try(U64, [RandomErr(IOErr)])
    pub fn hosted_random_seed_u64() -> TryType48;

    /// Hosted symbol for Sleep.millis!
    /// Roc signature: U64 => {}
    pub fn hosted_sleep_millis(arg0: u64);

    /// Hosted symbol for Stderr.line!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_line(arg0: RocStr) -> TryType58;

    /// Hosted symbol for Stderr.write!
    /// Roc signature: Str => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_write(arg0: RocStr) -> TryType58;

    /// Hosted symbol for Stderr.write_bytes!
    /// Roc signature: List(U8) => Try({}, [StderrErr(IOErr)])
    pub fn hosted_stderr_write_bytes(arg0: RocListWith<u8, false>) -> TryType58;

    /// Hosted symbol for Stdin.bytes!
    /// Roc signature: {} => Try(List(U8), [EndOfFile, StdinErr(IOErr)])
    pub fn hosted_stdin_bytes() -> TryType70;

    /// Hosted symbol for Stdin.line!
    /// Roc signature: {} => Try(Str, [EndOfFile, StdinErr(IOErr)])
    pub fn hosted_stdin_line() -> TryType65;

    /// Hosted symbol for Stdin.read_to_end!
    /// Roc signature: {} => Try(List(U8), [StdinErr(IOErr)])
    pub fn hosted_stdin_read_to_end() -> TryType73;

    /// Hosted symbol for Stdout.line!
    /// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
    pub fn hosted_stdout_line(arg0: RocStr) -> TryType75;

    /// Hosted symbol for Stdout.write!
    /// Roc signature: Str => Try({}, [StdoutErr(IOErr)])
    pub fn hosted_stdout_write(arg0: RocStr) -> TryType75;

    /// Hosted symbol for Stdout.write_bytes!
    /// Roc signature: List(U8) => Try({}, [StdoutErr(IOErr)])
    pub fn hosted_stdout_write_bytes(arg0: RocListWith<u8, false>) -> TryType75;

    /// Hosted symbol for Tty.disable_raw_mode!
    /// Roc signature: {} => {}
    pub fn hosted_tty_disable_raw_mode();

    /// Hosted symbol for Tty.enable_raw_mode!
    /// Roc signature: {} => {}
    pub fn hosted_tty_enable_raw_mode();

    /// Hosted symbol for Utc.now!
    /// Roc signature: {} => U128
    pub fn hosted_utc_now() -> u128;

}

/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
pub struct DefaultAllocators;

impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = length + size_storage_bytes;

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = new_length + size_storage_bytes;
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
pub struct DefaultHandlers;

impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: main_for_host!
    pub fn roc_main(arg0: RocList<RocStr>) -> i32;

}
