//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicIsize, Ordering};
use std::alloc::Layout;

/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub const fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    ROC_ERASED_CALLABLE_CAPTURE_OFFSET + capture_size
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let base = roc_host.alloc(alignment, extra_bytes + roc_erased_callable_payload_size(capture_size)) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
pub fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { roc_host.alloc(alloc_alignment, header_bytes + payload_size) } as *mut u8;
    let data = unsafe { base.add(header_bytes) };
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    decref_box_with(data_ptr, core::mem::align_of::<usize>(), None, roc_host);
}

/// Increment a boxed function closure.
pub fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    incref_box(callable as RocBox, amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    decref_box_with(
        callable as RocBox,
        ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
        Some(drop_erased_callable_payload),
        roc_host,
    );
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    unsafe {
        if (*rc).load(Ordering::Relaxed) == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
        if prev == 1 {
            if let Some(callback) = payload_decref {
                callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
            }
            free_box_allocation(data, payload_alignment, payload_decref.is_some(), roc_host);
        }
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_decref.is_some(), roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Relaxed) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { 2 * ptr_width } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`, assuming valid UTF-8.
    pub fn as_str(&self) -> &str {
        // SAFETY: Roc guarantees all strings are valid UTF-8.
        unsafe { core::str::from_utf8_unchecked(self.as_slice()) }
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = ptr_width + slice.len();
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: slice.len() << 1,
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let ptr_width = core::mem::size_of::<usize>();
                let base = (alloc_ptr as *mut u8).sub(ptr_width) as *mut c_void;
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("value", &self.as_str())
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { 2 * ptr_width } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    pub fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = length * core::mem::size_of::<T>();
        let total = data_bytes + header_bytes;
        let base = unsafe { roc_host.alloc(align, total) };
        let data_ptr = unsafe { (base as *mut u8).add(header_bytes) };
        // Write refcount = 1
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: length << 1,
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    pub fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = Self::allocate(slice.len(), roc_host);
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
            }
            let prev = (*rc).fetch_sub(1, Ordering::Relaxed);
            if prev == 1 {
                let base = alloc_ptr.sub(header_bytes) as *mut c_void;
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(&self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut AtomicIsize).sub(1);
            if (*rc).load(Ordering::Relaxed) == 0 {
                return; // REFCOUNT_STATIC_DATA
            }
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Relaxed);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Relaxed) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Element type for Cmd
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Cmd {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<Cmd>() == 80, "Cmd size mismatch");
const _: () = assert!(core::mem::align_of::<Cmd>() == 8, "Cmd alignment mismatch");

/// Element type for __AnonStruct10
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct10 {
    pub stderr_utf8_lossy: RocStr,
    pub stdout_utf8_lossy: RocStr,
    pub exit_code: i32,
}

const _: () = assert!(core::mem::size_of::<AnonStruct10>() == 56, "AnonStruct10 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct10>() == 8, "AnonStruct10 alignment mismatch");

/// Element type for __AnonStruct11
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct11 {
    pub stderr_utf8_lossy: RocStr,
    pub stdout_utf8: RocStr,
}

const _: () = assert!(core::mem::size_of::<AnonStruct11>() == 48, "AnonStruct11 size mismatch");
const _: () = assert!(core::mem::align_of::<AnonStruct11>() == 8, "AnonStruct11 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType0Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType0 {
    pub payload: TryType0Payload,
    pub tag: TryType0Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType0Payload {
    pub err: core::mem::ManuallyDrop<CmdIOErr>,
    pub ok: core::mem::ManuallyDrop<i32>,
}

const _: () = assert!(core::mem::size_of::<TryType0>() == 40, "TryType0 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType0>() == 8, "TryType0 alignment mismatch");

/// Tag discriminant for Cmd.IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CmdIOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: Cmd.IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdIOErr {
    pub payload: CmdIOErrPayload,
    pub tag: CmdIOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union CmdIOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<CmdIOErr>() == 32, "CmdIOErr size mismatch");
const _: () = assert!(core::mem::align_of::<CmdIOErr>() == 8, "CmdIOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType8Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType8 {
    pub payload: TryType8Payload,
    pub tag: TryType8Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType8Payload {
    pub err: core::mem::ManuallyDrop<CmdErrOrNonZeroExit>,
    pub ok: core::mem::ManuallyDrop<AnonStruct11>,
}

const _: () = assert!(core::mem::size_of::<TryType8>() == 72, "TryType8 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType8>() == 8, "TryType8 alignment mismatch");

/// Tag discriminant for CmdErrOrNonZeroExit.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CmdErrOrNonZeroExitTag {
    CmdErr = 0,
    NonZeroExit = 1,
}

/// Tag union: CmdErrOrNonZeroExit
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdErrOrNonZeroExit {
    pub payload: CmdErrOrNonZeroExitPayload,
    pub tag: CmdErrOrNonZeroExitTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union CmdErrOrNonZeroExitPayload {
    pub cmd_err: core::mem::ManuallyDrop<CmdIOErr>,
    pub non_zero_exit: core::mem::ManuallyDrop<AnonStruct10>,
}

const _: () = assert!(core::mem::size_of::<CmdErrOrNonZeroExit>() == 64, "CmdErrOrNonZeroExit size mismatch");
const _: () = assert!(core::mem::align_of::<CmdErrOrNonZeroExit>() == 8, "CmdErrOrNonZeroExit alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType12Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType12 {
    pub payload: TryType12Payload,
    pub tag: TryType12Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType12Payload {
    pub err: core::mem::ManuallyDrop<DirIOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType12>() == 40, "TryType12 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType12>() == 8, "TryType12 alignment mismatch");

/// Tag discriminant for Dir.IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DirIOErrTag {
    AlreadyExists = 0,
    NotADirectory = 1,
    NotEmpty = 2,
    NotFound = 3,
    Other = 4,
    PermissionDenied = 5,
}

/// Tag union: Dir.IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirIOErr {
    pub payload: DirIOErrPayload,
    pub tag: DirIOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union DirIOErrPayload {
    pub already_exists: [u8; 0],
    pub not_adirectory: [u8; 0],
    pub not_empty: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub permission_denied: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<DirIOErr>() == 32, "DirIOErr size mismatch");
const _: () = assert!(core::mem::align_of::<DirIOErr>() == 8, "DirIOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType17Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType17 {
    pub payload: TryType17Payload,
    pub tag: TryType17Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType17Payload {
    pub err: core::mem::ManuallyDrop<DirIOErr>,
    pub ok: core::mem::ManuallyDrop<RocList<RocStr>>,
}

const _: () = assert!(core::mem::size_of::<TryType17>() == 40, "TryType17 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType17>() == 8, "TryType17 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType21Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType21 {
    pub payload: TryType21Payload,
    pub tag: TryType21Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType21Payload {
    pub err: core::mem::ManuallyDrop<FileIOErr>,
    pub ok: core::mem::ManuallyDrop<RocListWith<u8, false>>,
}

const _: () = assert!(core::mem::size_of::<TryType21>() == 40, "TryType21 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType21>() == 8, "TryType21 alignment mismatch");

/// Tag discriminant for File.IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileIOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: File.IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileIOErr {
    pub payload: FileIOErrPayload,
    pub tag: FileIOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union FileIOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<FileIOErr>() == 32, "FileIOErr size mismatch");
const _: () = assert!(core::mem::align_of::<FileIOErr>() == 8, "FileIOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType27Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType27 {
    pub payload: TryType27Payload,
    pub tag: TryType27Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType27Payload {
    pub err: core::mem::ManuallyDrop<FileIOErr>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType27>() == 40, "TryType27 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType27>() == 8, "TryType27 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType29Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType29 {
    pub payload: TryType29Payload,
    pub tag: TryType29Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType29Payload {
    pub err: core::mem::ManuallyDrop<FileIOErr>,
    pub ok: core::mem::ManuallyDrop<RocStr>,
}

const _: () = assert!(core::mem::size_of::<TryType29>() == 40, "TryType29 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType29>() == 8, "TryType29 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType32Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType32 {
    pub payload: TryType32Payload,
    pub tag: TryType32Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType32Payload {
    pub err: core::mem::ManuallyDrop<PathIOErr>,
    pub ok: core::mem::ManuallyDrop<bool>,
}

const _: () = assert!(core::mem::size_of::<TryType32>() == 40, "TryType32 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType32>() == 8, "TryType32 alignment mismatch");

/// Tag discriminant for Path.IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PathIOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: Path.IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PathIOErr {
    pub payload: PathIOErrPayload,
    pub tag: PathIOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union PathIOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<PathIOErr>() == 32, "PathIOErr size mismatch");
const _: () = assert!(core::mem::align_of::<PathIOErr>() == 8, "PathIOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType37Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType37 {
    pub payload: TryType37Payload,
    pub tag: TryType37Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType37Payload {
    pub err: core::mem::ManuallyDrop<RandomIOErr>,
    pub ok: core::mem::ManuallyDrop<u64>,
}

const _: () = assert!(core::mem::size_of::<TryType37>() == 40, "TryType37 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType37>() == 8, "TryType37 alignment mismatch");

/// Tag discriminant for Random.IOErr.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RandomIOErrTag {
    AlreadyExists = 0,
    BrokenPipe = 1,
    Interrupted = 2,
    NotFound = 3,
    Other = 4,
    OutOfMemory = 5,
    PermissionDenied = 6,
    Unsupported = 7,
}

/// Tag union: Random.IOErr
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RandomIOErr {
    pub payload: RandomIOErrPayload,
    pub tag: RandomIOErrTag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union RandomIOErrPayload {
    pub already_exists: [u8; 0],
    pub broken_pipe: [u8; 0],
    pub interrupted: [u8; 0],
    pub not_found: [u8; 0],
    pub other: core::mem::ManuallyDrop<RocStr>,
    pub out_of_memory: [u8; 0],
    pub permission_denied: [u8; 0],
    pub unsupported: [u8; 0],
}

const _: () = assert!(core::mem::size_of::<RandomIOErr>() == 32, "RandomIOErr size mismatch");
const _: () = assert!(core::mem::align_of::<RandomIOErr>() == 8, "RandomIOErr alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType43Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType43 {
    pub payload: TryType43Payload,
    pub tag: TryType43Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType43Payload {
    pub err: core::mem::ManuallyDrop<RandomIOErr>,
    pub ok: core::mem::ManuallyDrop<u32>,
}

const _: () = assert!(core::mem::size_of::<TryType43>() == 40, "TryType43 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType43>() == 8, "TryType43 alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType59Tag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType59 {
    pub payload: TryType59Payload,
    pub tag: TryType59Tag,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType59Payload {
    pub err: core::mem::ManuallyDrop<i32>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<TryType59>() == 8, "TryType59 size mismatch");
const _: () = assert!(core::mem::align_of::<TryType59>() == 4, "TryType59 alignment mismatch");

/// Arguments for Cmd.exec_exit_code!
/// Roc signature: Cmd => Try(I32, [CmdErr(Cmd.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdExecExitCodeArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<CmdExecExitCodeArgs>() == 80, "CmdExecExitCodeArgs size mismatch");
const _: () = assert!(core::mem::align_of::<CmdExecExitCodeArgs>() == 8, "CmdExecExitCodeArgs alignment mismatch");

/// Arguments for Cmd.exec_output!
/// Roc signature: Cmd => Try({ stderr_utf8_lossy : Str, stdout_utf8 : Str }, [CmdErr(Cmd.IOErr), NonZeroExit({ exit_code : I32, stderr_utf8_lossy : Str, stdout_utf8_lossy : Str })])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CmdExecOutputArgs {
    pub args: RocList<RocStr>,
    pub envs: RocList<RocStr>,
    pub program: RocStr,
    pub clear_envs: bool,
}

const _: () = assert!(core::mem::size_of::<CmdExecOutputArgs>() == 80, "CmdExecOutputArgs size mismatch");
const _: () = assert!(core::mem::align_of::<CmdExecOutputArgs>() == 8, "CmdExecOutputArgs alignment mismatch");

/// Arguments for Dir.create!
/// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirCreateArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.create_all!
/// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirCreateAllArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.delete_all!
/// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirDeleteAllArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.delete_empty!
/// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirDeleteEmptyArgs {
    pub arg0: RocStr,
}

/// Arguments for Dir.list!
/// Roc signature: Str => Try(List(Str), [DirErr(Dir.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct DirListArgs {
    pub arg0: RocStr,
}

/// Arguments for Env.var!
/// Roc signature: Str => Str
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct EnvVarArgs {
    pub arg0: RocStr,
}

/// Arguments for File.delete!
/// Roc signature: Str => Try({}, [FileErr(File.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileDeleteArgs {
    pub arg0: RocStr,
}

/// Arguments for File.read_bytes!
/// Roc signature: Str => Try(List(U8), [FileErr(File.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileReadBytesArgs {
    pub arg0: RocStr,
}

/// Arguments for File.read_utf8!
/// Roc signature: Str => Try(Str, [FileErr(File.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileReadUtf8Args {
    pub arg0: RocStr,
}

/// Arguments for File.write_bytes!
/// Roc signature: Str, List(U8) => Try({}, [FileErr(File.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileWriteBytesArgs {
    pub arg0: RocStr,
    pub arg1: RocListWith<u8, false>,
}

/// Arguments for File.write_utf8!
/// Roc signature: Str, Str => Try({}, [FileErr(File.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct FileWriteUtf8Args {
    pub arg0: RocStr,
    pub arg1: RocStr,
}

/// Arguments for Path.is_dir!
/// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PathIsDirArgs {
    pub arg0: RocStr,
}

/// Arguments for Path.is_file!
/// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PathIsFileArgs {
    pub arg0: RocStr,
}

/// Arguments for Path.is_sym_link!
/// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PathIsSymLinkArgs {
    pub arg0: RocStr,
}

/// Arguments for Sleep.millis!
/// Roc signature: U64 => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SleepMillisArgs {
    pub arg0: u64,
}

/// Arguments for Stderr.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stderr.write!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StderrWriteArgs {
    pub arg0: RocStr,
}

/// Arguments for Stdout.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StdoutLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stdout.write!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct StdoutWriteArgs {
    pub arg0: RocStr,
}

// =============================================================================
// Generated Refcount Helpers
// =============================================================================

/// Recursively decrement Roc-owned payloads in TryType0.
pub fn decref_try_type0(value: TryType0, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_cmd_ioerr(payload, roc_host);
        },
        TryType0Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType0.
pub fn incref_try_type0(value: TryType0, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType0Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_cmd_ioerr(payload, amount);
        },
        TryType0Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in CmdIOErr.
pub fn decref_cmd_ioerr(value: CmdIOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        CmdIOErrTag::AlreadyExists => {},
        CmdIOErrTag::BrokenPipe => {},
        CmdIOErrTag::Interrupted => {},
        CmdIOErrTag::NotFound => {},
        CmdIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        CmdIOErrTag::OutOfMemory => {},
        CmdIOErrTag::PermissionDenied => {},
        CmdIOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in CmdIOErr.
pub fn incref_cmd_ioerr(value: CmdIOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        CmdIOErrTag::AlreadyExists => {},
        CmdIOErrTag::BrokenPipe => {},
        CmdIOErrTag::Interrupted => {},
        CmdIOErrTag::NotFound => {},
        CmdIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        CmdIOErrTag::OutOfMemory => {},
        CmdIOErrTag::PermissionDenied => {},
        CmdIOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned fields in Cmd.
pub fn decref_cmd(value: Cmd, roc_host: &RocHost) {
    {
        let list = value.args;
        if list.has_one_ref() {
            for item in list.allocation_items().iter().copied() {
                    item.decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        let list = value.envs;
        if list.has_one_ref() {
            for item in list.allocation_items().iter().copied() {
                    item.decref(roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.program.decref(roc_host);
}

/// Increment Roc-owned fields in Cmd.
pub fn incref_cmd(value: Cmd, amount: isize) {
    value.args.incref(amount);
    value.envs.incref(amount);
    value.program.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType8.
pub fn decref_try_type8(value: TryType8, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType8Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_cmd_err_or_non_zero_exit(payload, roc_host);
        },
        TryType8Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            decref_anon_struct11(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType8.
pub fn incref_try_type8(value: TryType8, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType8Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_cmd_err_or_non_zero_exit(payload, amount);
        },
        TryType8Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            incref_anon_struct11(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in CmdErrOrNonZeroExit.
pub fn decref_cmd_err_or_non_zero_exit(value: CmdErrOrNonZeroExit, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        CmdErrOrNonZeroExitTag::CmdErr => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.cmd_err);
            decref_cmd_ioerr(payload, roc_host);
        },
        CmdErrOrNonZeroExitTag::NonZeroExit => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.non_zero_exit);
            decref_anon_struct10(payload, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in CmdErrOrNonZeroExit.
pub fn incref_cmd_err_or_non_zero_exit(value: CmdErrOrNonZeroExit, amount: isize) {
    let _ = amount;
    match value.tag {
        CmdErrOrNonZeroExitTag::CmdErr => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.cmd_err);
            incref_cmd_ioerr(payload, amount);
        },
        CmdErrOrNonZeroExitTag::NonZeroExit => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.non_zero_exit);
            incref_anon_struct10(payload, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in AnonStruct10.
pub fn decref_anon_struct10(value: AnonStruct10, roc_host: &RocHost) {
    value.stderr_utf8_lossy.decref(roc_host);
    value.stdout_utf8_lossy.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct10.
pub fn incref_anon_struct10(value: AnonStruct10, amount: isize) {
    value.stderr_utf8_lossy.incref(amount);
    value.stdout_utf8_lossy.incref(amount);
}

/// Recursively decrement Roc-owned fields in AnonStruct11.
pub fn decref_anon_struct11(value: AnonStruct11, roc_host: &RocHost) {
    value.stderr_utf8_lossy.decref(roc_host);
    value.stdout_utf8.decref(roc_host);
}

/// Increment Roc-owned fields in AnonStruct11.
pub fn incref_anon_struct11(value: AnonStruct11, amount: isize) {
    value.stderr_utf8_lossy.incref(amount);
    value.stdout_utf8.incref(amount);
}

/// Recursively decrement Roc-owned payloads in TryType12.
pub fn decref_try_type12(value: TryType12, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType12Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_dir_ioerr(payload, roc_host);
        },
        TryType12Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType12.
pub fn incref_try_type12(value: TryType12, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType12Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_dir_ioerr(payload, amount);
        },
        TryType12Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in DirIOErr.
pub fn decref_dir_ioerr(value: DirIOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        DirIOErrTag::AlreadyExists => {},
        DirIOErrTag::NotADirectory => {},
        DirIOErrTag::NotEmpty => {},
        DirIOErrTag::NotFound => {},
        DirIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        DirIOErrTag::PermissionDenied => {},
    }
}

/// Increment Roc-owned payloads in DirIOErr.
pub fn incref_dir_ioerr(value: DirIOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        DirIOErrTag::AlreadyExists => {},
        DirIOErrTag::NotADirectory => {},
        DirIOErrTag::NotEmpty => {},
        DirIOErrTag::NotFound => {},
        DirIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        DirIOErrTag::PermissionDenied => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType17.
pub fn decref_try_type17(value: TryType17, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType17Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_dir_ioerr(payload, roc_host);
        },
        TryType17Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                if list.has_one_ref() {
                    for item in list.allocation_items().iter().copied() {
                            item.decref(roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType17.
pub fn incref_try_type17(value: TryType17, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType17Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_dir_ioerr(payload, amount);
        },
        TryType17Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType21.
pub fn decref_try_type21(value: TryType21, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType21Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_file_ioerr(payload, roc_host);
        },
        TryType21Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            {
                let list = payload;
                list.decref(roc_host);
            }
        },
    }
}

/// Increment Roc-owned payloads in TryType21.
pub fn incref_try_type21(value: TryType21, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType21Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_file_ioerr(payload, amount);
        },
        TryType21Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in FileIOErr.
pub fn decref_file_ioerr(value: FileIOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        FileIOErrTag::AlreadyExists => {},
        FileIOErrTag::BrokenPipe => {},
        FileIOErrTag::Interrupted => {},
        FileIOErrTag::NotFound => {},
        FileIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        FileIOErrTag::OutOfMemory => {},
        FileIOErrTag::PermissionDenied => {},
        FileIOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in FileIOErr.
pub fn incref_file_ioerr(value: FileIOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        FileIOErrTag::AlreadyExists => {},
        FileIOErrTag::BrokenPipe => {},
        FileIOErrTag::Interrupted => {},
        FileIOErrTag::NotFound => {},
        FileIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        FileIOErrTag::OutOfMemory => {},
        FileIOErrTag::PermissionDenied => {},
        FileIOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType27.
pub fn decref_try_type27(value: TryType27, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType27Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_file_ioerr(payload, roc_host);
        },
        TryType27Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType27.
pub fn incref_try_type27(value: TryType27, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType27Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_file_ioerr(payload, amount);
        },
        TryType27Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType29.
pub fn decref_try_type29(value: TryType29, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType29Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_file_ioerr(payload, roc_host);
        },
        TryType29Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in TryType29.
pub fn incref_try_type29(value: TryType29, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType29Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_file_ioerr(payload, amount);
        },
        TryType29Tag::Ok => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.ok);
            payload.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in TryType32.
pub fn decref_try_type32(value: TryType32, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType32Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_path_ioerr(payload, roc_host);
        },
        TryType32Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType32.
pub fn incref_try_type32(value: TryType32, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType32Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_path_ioerr(payload, amount);
        },
        TryType32Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in PathIOErr.
pub fn decref_path_ioerr(value: PathIOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        PathIOErrTag::AlreadyExists => {},
        PathIOErrTag::BrokenPipe => {},
        PathIOErrTag::Interrupted => {},
        PathIOErrTag::NotFound => {},
        PathIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        PathIOErrTag::OutOfMemory => {},
        PathIOErrTag::PermissionDenied => {},
        PathIOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in PathIOErr.
pub fn incref_path_ioerr(value: PathIOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        PathIOErrTag::AlreadyExists => {},
        PathIOErrTag::BrokenPipe => {},
        PathIOErrTag::Interrupted => {},
        PathIOErrTag::NotFound => {},
        PathIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        PathIOErrTag::OutOfMemory => {},
        PathIOErrTag::PermissionDenied => {},
        PathIOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType37.
pub fn decref_try_type37(value: TryType37, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType37Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_random_ioerr(payload, roc_host);
        },
        TryType37Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType37.
pub fn incref_try_type37(value: TryType37, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType37Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_random_ioerr(payload, amount);
        },
        TryType37Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in RandomIOErr.
pub fn decref_random_ioerr(value: RandomIOErr, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        RandomIOErrTag::AlreadyExists => {},
        RandomIOErrTag::BrokenPipe => {},
        RandomIOErrTag::Interrupted => {},
        RandomIOErrTag::NotFound => {},
        RandomIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.decref(roc_host);
        },
        RandomIOErrTag::OutOfMemory => {},
        RandomIOErrTag::PermissionDenied => {},
        RandomIOErrTag::Unsupported => {},
    }
}

/// Increment Roc-owned payloads in RandomIOErr.
pub fn incref_random_ioerr(value: RandomIOErr, amount: isize) {
    let _ = amount;
    match value.tag {
        RandomIOErrTag::AlreadyExists => {},
        RandomIOErrTag::BrokenPipe => {},
        RandomIOErrTag::Interrupted => {},
        RandomIOErrTag::NotFound => {},
        RandomIOErrTag::Other => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.other);
            payload.incref(amount);
        },
        RandomIOErrTag::OutOfMemory => {},
        RandomIOErrTag::PermissionDenied => {},
        RandomIOErrTag::Unsupported => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType43.
pub fn decref_try_type43(value: TryType43, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType43Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            decref_random_ioerr(payload, roc_host);
        },
        TryType43Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType43.
pub fn incref_try_type43(value: TryType43, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType43Tag::Err => unsafe {
            let payload = core::mem::ManuallyDrop::into_inner(value.payload.err);
            incref_random_ioerr(payload, amount);
        },
        TryType43Tag::Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TryType59.
pub fn decref_try_type59(value: TryType59, roc_host: &RocHost) {
    let _ = roc_host;
    match value.tag {
        TryType59Tag::Err => {},
        TryType59Tag::Ok => {},
    }
}

/// Increment Roc-owned payloads in TryType59.
pub fn incref_try_type59(value: TryType59, amount: isize) {
    let _ = amount;
    match value.tag {
        TryType59Tag::Err => {},
        TryType59Tag::Ok => {},
    }
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Hosted symbol for Cmd.exec_exit_code!
    /// Roc signature: Cmd => Try(I32, [CmdErr(Cmd.IOErr)])
    pub fn hosted_cmd_exec_exit_code(arg0: Cmd) -> TryType0;

    /// Hosted symbol for Cmd.exec_output!
    /// Roc signature: Cmd => Try({ stderr_utf8_lossy : Str, stdout_utf8 : Str }, [CmdErr(Cmd.IOErr), NonZeroExit({ exit_code : I32, stderr_utf8_lossy : Str, stdout_utf8_lossy : Str })])
    pub fn hosted_cmd_exec_output(arg0: Cmd) -> TryType8;

    /// Hosted symbol for Dir.create!
    /// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
    pub fn hosted_dir_create(arg0: RocStr) -> TryType12;

    /// Hosted symbol for Dir.create_all!
    /// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
    pub fn hosted_dir_create_all(arg0: RocStr) -> TryType12;

    /// Hosted symbol for Dir.delete_all!
    /// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
    pub fn hosted_dir_delete_all(arg0: RocStr) -> TryType12;

    /// Hosted symbol for Dir.delete_empty!
    /// Roc signature: Str => Try({}, [DirErr(Dir.IOErr)])
    pub fn hosted_dir_delete_empty(arg0: RocStr) -> TryType12;

    /// Hosted symbol for Dir.list!
    /// Roc signature: Str => Try(List(Str), [DirErr(Dir.IOErr)])
    pub fn hosted_dir_list(arg0: RocStr) -> TryType17;

    /// Hosted symbol for Env.cwd!
    /// Roc signature: {} => Str
    pub fn hosted_env_cwd() -> RocStr;

    /// Hosted symbol for Env.exe_path!
    /// Roc signature: {} => Str
    pub fn hosted_env_exe_path() -> RocStr;

    /// Hosted symbol for Env.var!
    /// Roc signature: Str => Str
    pub fn hosted_env_var(arg0: RocStr) -> RocStr;

    /// Hosted symbol for File.delete!
    /// Roc signature: Str => Try({}, [FileErr(File.IOErr)])
    pub fn hosted_file_delete(arg0: RocStr) -> TryType27;

    /// Hosted symbol for File.read_bytes!
    /// Roc signature: Str => Try(List(U8), [FileErr(File.IOErr)])
    pub fn hosted_file_read_bytes(arg0: RocStr) -> TryType21;

    /// Hosted symbol for File.read_utf8!
    /// Roc signature: Str => Try(Str, [FileErr(File.IOErr)])
    pub fn hosted_file_read_utf8(arg0: RocStr) -> TryType29;

    /// Hosted symbol for File.write_bytes!
    /// Roc signature: Str, List(U8) => Try({}, [FileErr(File.IOErr)])
    pub fn hosted_file_write_bytes(arg0: RocStr, arg1: RocListWith<u8, false>) -> TryType27;

    /// Hosted symbol for File.write_utf8!
    /// Roc signature: Str, Str => Try({}, [FileErr(File.IOErr)])
    pub fn hosted_file_write_utf8(arg0: RocStr, arg1: RocStr) -> TryType27;

    /// Hosted symbol for Locale.all!
    /// Roc signature: {} => List(Str)
    pub fn hosted_locale_all() -> RocList<RocStr>;

    /// Hosted symbol for Locale.get!
    /// Roc signature: {} => Str
    pub fn hosted_locale_get() -> RocStr;

    /// Hosted symbol for Path.is_dir!
    /// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
    pub fn hosted_path_is_dir(arg0: RocStr) -> TryType32;

    /// Hosted symbol for Path.is_file!
    /// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
    pub fn hosted_path_is_file(arg0: RocStr) -> TryType32;

    /// Hosted symbol for Path.is_sym_link!
    /// Roc signature: Str => Try(Bool, [PathErr(Path.IOErr)])
    pub fn hosted_path_is_sym_link(arg0: RocStr) -> TryType32;

    /// Hosted symbol for Random.seed_u32!
    /// Roc signature: {} => Try(U32, [RandomErr(Random.IOErr)])
    pub fn hosted_random_seed_u32() -> TryType43;

    /// Hosted symbol for Random.seed_u64!
    /// Roc signature: {} => Try(U64, [RandomErr(Random.IOErr)])
    pub fn hosted_random_seed_u64() -> TryType37;

    /// Hosted symbol for Sleep.millis!
    /// Roc signature: U64 => {}
    pub fn hosted_sleep_millis(arg0: u64);

    /// Hosted symbol for Stderr.line!
    /// Roc signature: Str => {}
    pub fn hosted_stderr_line(arg0: RocStr);

    /// Hosted symbol for Stderr.write!
    /// Roc signature: Str => {}
    pub fn hosted_stderr_write(arg0: RocStr);

    /// Hosted symbol for Stdin.line!
    /// Roc signature: {} => Str
    pub fn hosted_stdin_line() -> RocStr;

    /// Hosted symbol for Stdout.line!
    /// Roc signature: Str => {}
    pub fn hosted_stdout_line(arg0: RocStr);

    /// Hosted symbol for Stdout.write!
    /// Roc signature: Str => {}
    pub fn hosted_stdout_write(arg0: RocStr);

    /// Hosted symbol for Tty.disable_raw_mode!
    /// Roc signature: {} => {}
    pub fn hosted_tty_disable_raw_mode();

    /// Hosted symbol for Tty.enable_raw_mode!
    /// Roc signature: {} => {}
    pub fn hosted_tty_enable_raw_mode();

    /// Hosted symbol for Utc.now!
    /// Roc signature: {} => U128
    pub fn hosted_utc_now() -> u128;

}

/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
pub struct DefaultAllocators;

impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = length + size_storage_bytes;

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = new_length + size_storage_bytes;
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
pub struct DefaultHandlers;

impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: main_for_host!
    pub fn roc_main(arg0: RocList<RocStr>) -> i32;

}
